# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u94fe\u63a5\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-add_time'],
                'verbose_name': '\u597d\u7684\u6587\u7ae0\u94fe\u63a5',
                'verbose_name_plural': '\u597d\u7684\u6587\u7ae0\u94fe\u63a5',
            },
        ),
    ]
