# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_goodlink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodlink',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a8\u8350'),
        ),
    ]
