# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_goodlink_is_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('index', models.IntegerField(default=999, verbose_name='\u5206\u7c7b\u7684\u6392\u5e8f')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '\u56fe\u7247\u5206\u7c7b',
                'verbose_name_plural': '\u56fe\u7247\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u56fe\u7247\u6807\u9898')),
                ('image', models.ImageField(max_length=200, upload_to=b'', verbose_name='\u56fe\u7247')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.PictureCategory', verbose_name='\u56fe\u7247\u5206\u7c7b')),
            ],
            options={
                'ordering': ['-add_time'],
                'verbose_name': '\u597d\u7684\u6587\u7ae0\u94fe\u63a5',
                'verbose_name_plural': '\u597d\u7684\u6587\u7ae0\u94fe\u63a5',
            },
        ),
    ]
