# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180614_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u540d\u5b57')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u7bb1\u5730\u5740')),
                ('content', models.TextField(max_length=1000, verbose_name='\u5185\u5bb9')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u6536\u5230\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-date_publish'],
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(max_length=200, upload_to='pictures', verbose_name='\u56fe\u7247'),
        ),
    ]
