# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180614_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('cls', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u540d\u5b57\u6837\u5f0f')),
                ('desc', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u4ecb\u7ecd')),
                ('url', models.URLField(verbose_name='\u9879\u76ee\u5730\u5740')),
                ('index', models.IntegerField(default=999, verbose_name='\u6392\u5e8f\uff08\u4ece\u5c0f\u5230\u5927\uff09')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '\u6211\u7684\u9879\u76ee',
                'verbose_name_plural': '\u6211\u7684\u9879\u76ee',
            },
        ),
    ]
