# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180615_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='url',
            field=models.CharField(default='#', max_length=200, verbose_name='\u9879\u76ee\u5730\u5740'),
        ),
    ]
