# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180615_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='\u9879\u76ee\u4ecb\u7ecd'),
        ),
    ]
